### ISSUE TITLE
READMEどおりcloneしても動かない

### ISSUE THREAD

**Issue by taka-tuos** [cobodo/mikutter-worldon#11]
表題の通りです。
./mikutter.rb --debug > miku.log 2>&1 で取得したログを添付しておきます。
[miku.log](https://github.com/cobodo/mikutter-worldon/files/1773754/miku.log)

**Comment by cobodo** [comment]
報告ありがとうございます。
設定がない状態からの初期化処理に問題があったようなので修正しました。現在のmasterで確認してもらえますか？

**Comment by taka-tuos** [comment]
rubyごと必ずSIGABRTで落ちるようになってしまいましたね…

**Comment by cobodo** [comment]
ということはrubyのバージョンの問題っぽいですね。あとで2.3.6でも試してみることにします。

**Comment by taka-tuos** [comment]
2.3.3でしたね…
2.4今から入れてみます
そういう問題ならREADMEにバージョン表記したほうがいいかなって思いますね

**Comment by cobodo** [comment]
mikutter本体は2.3以降 http://mikutter.hatenablog.com/entry/2017/12/25/012351 ということになっていますが、僕自身は2.5.0でしか試していないんですよ。
別のバージョンで試すこと自体はrbenvで（gemを含めたビルドにかかる時間を考慮しなければ）すぐできるので、まず試してみて、対応できそうなら2.3でも動くようにしますし、キツそうなら要求バージョンを追記するかもしれません。

**Comment by taka-tuos** [comment]
2.4.0で動作確認しました。(起動->アカウント登録)

**Comment by taka-tuos** [comment]
でもまだ落ちますね…
ログ添付します
[miku (1).log](https://github.com/cobodo/mikutter-worldon/files/1774114/miku.1.log)

**Comment by cobodo** [comment]
対策しました。手元のruby-2.3.6で動いているので恐らく大丈夫だと思います。試してもらえますか？

**Comment by taka-tuos** [comment]
2.5にして解決しましたのでご報告します(所要時間3h…)

**Comment by taka-tuos** [comment]
2.3.6やってみますね

**Comment by taka-tuos** [comment]
2.3.3p222で動作確認しました
修正ありがとうございました。

**Comment by cobodo** [comment]
確認ありがとうございます。それでは閉じますね。
