### ISSUE TITLE
リプライ先の本文表示部分で<a>タグが見えてしまっている

### ISSUE THREAD

**Issue by taka-tuos** [cobodo/mikutter-worldon#12]
表題の通りです。
特に影響があるというわけではないですが気になったのでissue立てさせていただきました。

**Comment by cobodo** [comment]
これは微妙な問題でして。
twitterと同じ形式でEntityを作れば対応できるんですが、mikutter本体側でEntityを大幅に刷新する新機能が開発中で、今対応してもすぐにそちらで置き換えられると予想されるため、放置しています。
気になるのはとてもわかります（僕も気になります）が、他にやることがなくなっても本体側の更新が来ないような状況にならない限り着手しません。
新Entityではこの問題に対応できるだけでなく、カスタム絵文字の表示や、mikutter-subparts-imageのような外部プラグインなしで添付画像をインライン表示したりできる予定だと伺っているので、お楽しみに。

**Comment by cobodo** [comment]
@taka-tuos 
別の方法で、<a>タグが出ないようにする修正をmasterに入れました。時間がある時にでも試してみてください。

**Comment by cobodo** [comment]
mikutter 3.7対応で根本的に解決されたのでcloseします
