### ISSUE TITLE
投稿先の素早い切り換え方法の提供

### ISSUE THREAD

**Issue by ncaq** [cobodo/mikutter-worldon#41]
TwitterとMastodonを両方使っているので,<kbd>Enter</kbd>でTwitterに投稿し,<kbd>M-Enter</kbd>で所属するmastodonに投稿するということを行いたいです.
現在のアカウントをマウスでポチポチクリックして切り替える手法はかなり面倒です.
もしかしたらアカウント切り替えに関する機能だからmikutter本体に入れるべきかもしれませんが…
とりあえず対処したい問題はworldon使用時の時だけなのでこちらにissue建ててみます.

**Comment by cobodo** [comment]
こういった話はちょいちょい見かけるので紹介記事を書きました。
https://cobodo.hateblo.jp/entry/2018/05/09/175138

結論としてはworldonの問題でもコアの問題でもなく、worldプラグイン（本体同梱）やchange_accountプラグイン（本体同梱）の機能不足に起因する話なので、別のプラグインを入れてなんとかすることができる、ということです。
