### ISSUE TITLE
連合/ローカルタイムライン表示時にエラー (NoMethodError)

### ISSUE THREAD

**Issue by ascamik** [cobodo/mikutter-worldon#58]
mikutter3.7.2.
停止はせず、表面上動作はしているように見えますが、連合またはローカルタイムラインを表示すると、断続的にエラーを吐きます. 下記はエラーの一部.
```
#<Thread:0x00007fb370177d90@/home/username/.mikutter/plugin/worldon/sse_stream.rb:214 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	9: from /home/username/.mikutter/plugin/worldon/sse_stream.rb:216:in `block (3 levels) in <top (required)>'
	8: from /home/username/.mikutter/plugin/worldon/sse_stream.rb:254:in `update_handler'
	7: from /home/username/.mikutter/plugin/worldon/model/status.rb:80:in `build'
	6: from /home/username/.mikutter/plugin/worldon/model/status.rb:80:in `map'
	5: from /home/username/.mikutter/plugin/worldon/model/status.rb:81:in `block in build'
	4: from /home/username/.mikutter/plugin/worldon/model/status.rb:102:in `json2status'
	3: from /home/username/.mikutter/plugin/worldon/model/status.rb:137:in `merge_or_create'
	2: from /home/username/Downloads/mikutter/core/lib/weakstorage.rb:194:in `[]='
	1: from /home/username/Downloads/mikutter/vendor/diva/model.rb:61:in `hash'
/home/username/Downloads/mikutter/vendor/diva/model_extend.rb:39:in `block in add_field': undefined method `[]' for nil:NilClass (NoMethodError)
#<Thread:0x00007fb310047750@/home/username/.mikutter/plugin/worldon/sse_stream.rb:214 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	9: from /home/username/.mikutter/plugin/worldon/sse_stream.rb:216:in `block (3 levels) in <top (required)>'
	8: from /home/username/.mikutter/plugin/worldon/sse_stream.rb:254:in `update_handler'
	7: from /home/username/.mikutter/plugin/worldon/model/status.rb:80:in `build'
	6: from /home/username/.mikutter/plugin/worldon/model/status.rb:80:in `map'
	5: from /home/username/.mikutter/plugin/worldon/model/status.rb:81:in `block in build'
	4: from /home/username/.mikutter/plugin/worldon/model/status.rb:102:in `json2status'
	3: from /home/username/.mikutter/plugin/worldon/model/status.rb:137:in `merge_or_create'
	2: from /home/username/Downloads/mikutter/core/lib/weakstorage.rb:194:in `[]='
	1: from /home/username/Downloads/mikutter/vendor/diva/model.rb:61:in `hash'
/home/username/Downloads/mikutter/vendor/diva/model_extend.rb:39:in `block in add_field': undefined method `[]' for nil:NilClass (NoMethodError)
```

**Comment by cobodo** [comment]
報告ありがとうございます。
しかし私の環境では再現しません。

パスから察するにdivaをbundler以外の方法でインストールされているんでしょうか？
rubyやdivaのバージョン、worldonのcommit hash、具体的な利用環境など、もう少し詳しく教えてもらってもいいですか？

**Comment by ascamik** [comment]
レスありがとうございます。各々のバージョンですが次のとおりです。
Ruby 2.5.0
diva 0.3.2
worldon #7c5712ff887e50eee1074eed59d196cc0e72b79c

使用している環境はGentoo Linuxで、解凍したMikutterのvendorディレクトリを消して、
bundle install  --path vendor
してます。
（試しに消さずにbundle install  --path vendor/bundle をするとv2.jsonがないとか怒られたため、手動でv2.jsonを入れてみました。添付の--debug出力はこの方法で入れたものの出力を貼り付けてしまいましたが、このインストール方法の違いでエラーは（パス以外）変わりませんでした）

その後、動作確認した後で、/usr/share/mikutter/へコピーしています。

以上ご参考まで。

#どのユーザのトゥートで出てるのかはっきりすればしぼりこめるかもしれませんが；

**Comment by cobodo** [comment]
うーん、至って普通の環境ですね。

> /usr/share/mikutter/へコピーしています。

というのはよくわかりませんけど……

あと、それが発生するMastodonインスタンスのドメインを教えてもらってもいいですか？


エラーの内容としては、`Diva::Model`のフィールドを格納する`Hash`型のインスタンス変数`@value`が`nil`だと言っているわけですが、この変数は`Diva::Model#initialize`で引数（`Hash`）を使って初期化されるので、`nil`にはならないはずだと思うんですよね。

worldon/model/status.rb の 137行目
```ruby
@@status_storage[uri] = status
```
の直前に
```ruby
pp uri
$stdout.flush
```
を仕込むと、エラーメッセージの前に該当トゥートのURIが表示できると思うので、試してみてもらえますか？

**Comment by ascamik** [comment]
試してみました。
エラーの出ているトゥートは、ミュートしているアカウントのトゥートです。
ミュートの機能は動いているようで当然というか、トゥート自体はMikutter上には表示されてません。

大量の投稿をしているアカウントをミュートしているため、多くのエラーが断続的に出る挙動になったようです。
ちなみに利用しているインスタンスはmstdn.jpです。


（/usr/share/mikutter はかつてパッケージマネージャでMikutterをインストールしたときの位置で、なんとなくそこへ今でもインストールしているという…)

**Comment by ncaq** [comment]
ミュート機能が動くようになってinitializeがミュート時早期リターンするようになって(書いたのは私)
埋められるべきフィールドが埋められなくてエラー?
initializeはnil返してもクラスのインスタンス自体は出来てしまいますからね
ミュートした時にインスタンス変数を設定してmerge_or_createあたりで分岐する?
こちらの環境だと再現しないので修正が難しい

**Comment by cobodo** [comment]
> エラーの出ているトゥートは、ミュートしているアカウントのトゥートです。

> initializeはnil返してもクラスのインスタンス自体は出来てしまいますからね
> ミュートした時にインスタンス変数を設定してmerge_or_createあたりで分岐する?

なるほど、そうだったんですね。
次は分岐する位置を変えたコードを書いて試してみてもらうのがよさそうですね。

**Comment by ascamik** [comment]
ncaqさん、コメントありがとうございます。このエラーはRuby2.5からデフォルトで有効になったみたいですね。まだ他にも環境が関係するのかもわかりませんが。

フォークしてsse_stream.rbとrest.rbへミュート判定を移動してみました。こちらの環境では一応動いているようにみえますが、これで良いのかな。テストしてもらえば有り難いです。スキル無くてこのくらいしか書けませんで申し訳ないです;

**Comment by cobodo** [comment]
@ascamik パッチ見ました。しかし例えばトゥートのURLを引用した場合など、streamでもrestでもない手段で取得される`Status`というものが存在し、そういったものにもミュート判定は効かせたいため、移動先が不適切であると考えました。

包括的に扱えてしかもコンストラクタの外になる位置に移動させる修正をmasterにpushしましたので、確認していただけますか？
