### ISSUE TITLE
Module#.memoizeが呼び出されている

### ISSUE THREAD

**Issue by ncaq** [cobodo/mikutter-worldon#60]
以下の警告が出ます.

~~~
warning: /home/ncaq/.mikutter/plugin/worldon/model/emoji.rb:15:in `<class:Emoji>': Module#.memoize called in /home/ncaq/.mikutter/plugin/worldon/model/emoji.rb:15:in `<class:Emoji>'.
warning: /home/ncaq/.mikutter/plugin/worldon/model/emoji.rb:15:in `<class:Emoji>': see https://dev.mikutter.hachune.net/issues/1051
~~~

> 今後は、memoizeメソッドを利用する場合は、そのClassやModuleにMemoistをextendするという、memoistのマニュアルに書いてある方法をmikutterプラグインにも利用してもらうようにします。そのうえで、Module#.memoizeも実装しておいて、extendしていない旧来のプラグインも利用できるようにします。その場合はmemoizeが呼ばれた時に警告を発生させます。
> 
> この警告が表示されるようになってしまったプラグインは、memoistの使い方 を参考に書き直すべきです。memoistはもともと利用するClassやModuleにextendするのが正しい使い方だったので、そのような書き換えを行っても、memoist 1.15以前+mikutter 3.5.8以前を利用している環境でも正しく動きます。
>
> [環境対応 #1051: memoistを1.16にアップデートすると起動しなくなる - mikutter - やること](https://dev.mikutter.hachune.net/issues/1051)

**Comment by cobodo** [comment]
修正してmasterにpushしたので確認してもらえますか？

**Comment by ncaq** [comment]
spell.rb
にもmemoizeありますけどこれ呼び出されないのか表示がされないですね

**Comment by ncaq** [comment]
なるほど~まあまだ警告段階なのでもし問題だとしても問題になってから深刻に考えてもよさそうですね
警告自体は消えたのでcloseします
