### ISSUE TITLE
v2.4.3のインスタンスの追加に失敗する

### ISSUE THREAD

**Issue by kazu0617** [cobodo/mikutter-worldon#65]
タイトル通りなのですが、神崎丼(いわゆるMastodonのmasterになるべく合わせたインスタンス)を追加しようとした際に認証コードを入力したものの「認証に失敗しました」と表示されてしまいます。

**Comment by cobodo** [comment]
報告ありがとうございます。こちらでもテストしてみたいので、失敗したインスタンスのドメインを教えてもらえますか？

**Comment by kazu0617** [comment]
一応両方載せておきます
失敗したドメイン
`knzk.me`
`social.mikutter.hachune.net`
成功したドメイン
`mstdn.jp` `pawoo.net` `friends.nico`

なお、あまりにも情報が少なかったのでいろいろ捕捉します…
OS: Ubuntu 18.04 on Windows (WSL)
Version: mikutter3.7.4

また、その後クラッシュしていますので、そちらのログに関してもあわせて添付します(これに関しては最初関係ないかもしれないと思ったので貼ってなかったです)…
```
RuntimeError error has occurred at /oauth/token
{MIKUTTER_DIR}/core/plugin/change_account/change_account.rb:85:in `instance_eval'
{MIKUTTER_DIR}/core/plugin/change_account/change_account.rb:85:in `block (3 levels) in <top (required)>'
{MIKUTTER_DIR}/core/plugin/gtk/dialog_window.rb:191:in `instance_eval'
{MIKUTTER_DIR}/core/plugin/gtk/dialog_window.rb:191:in `block (2 levels) in run'
```

**Comment by cobodo** [comment]
具体的に何をしようとした時に発生したのでしょうか？ 「Worldを追加」ですか？

**Comment by kazu0617** [comment]
Worldを追加、ですね。
公開タイムラインの追加のほうでは正常に追加が成功しています。

**Comment by kazu0617** [comment]
ありがとうございます。試したところ、9.の操作を行い、OKを押した後強制的にクラッシュします。
その後起動した際に出たクラッシュログは以下の通りです。
```
RuntimeError error has occurred at verify_credentials
{MIKUTTER_DIR}/core/plugin/change_account/change_account.rb:85:in `instance_eval'
{MIKUTTER_DIR}/core/plugin/change_account/change_account.rb:85:in `block (3 levels) in <top (required)>'
{MIKUTTER_DIR}/core/plugin/gtk/dialog_window.rb:191:in `instance_eval'
{MIKUTTER_DIR}/core/plugin/gtk/dialog_window.rb:191:in `block (2 levels) in run'
```

**Comment by cobodo** [comment]
mikutterの起動時に`--debug`オプションを付けると、より詳細なメッセージがコンソールに表示されるようになるので、一度以下のようにログを採取してもらえますか？

```shell-session
$ ruby mikutter.rb --debug 2>&1 | tee debug.log
```

**Comment by cobodo** [comment]
ありがとうございます。
ログを見る限り、「アクセストークン」をコピーする際に、先頭にタブ文字が混ざってしまっているように見受けられます。コピペする際にはトークンだけが入るようにしてみてください。

**Comment by kazu0617** [comment]
確かに両方ともタブ文字が入ってました…すみませんでしたm(__)m

（認証に失敗してOKを押した後、クラッシュする問題に関しては別Issueとして建てたほうが良いですか？)

**Comment by cobodo** [comment]
> 認証に失敗してOKを押した後、クラッシュする問題に関しては別Issueとして建てたほうが良いですか？

こちらはmikutter本体の問題なので、プラグイン側ではどうにもなりません。mikutter redmineの該当issueのリンクを貼っておきますが、サーバ障害が発生中なので現在は確認できません。しばらく経って復旧されたら確認してみてください。

https://dev.mikutter.hachune.net/issues/1283

この件はこれでクローズとします。
