### ISSUE TITLE
リプライに関して「投稿する」コマンドから投稿した際、リプライがひっついてこない

### ISSUE THREAD

**Issue by kazu0617** [cobodo/mikutter-worldon#75]
書いたとおりです。
リプライものに関して、ショートカットキーに指定されている「投稿する」を発動した際にリプライとひっつかずに残ってしまい、投稿の方はそのまま投稿（いわゆる「空リプ」状態）されてしまいます。
![screenshot from 2018-09-10 01-00-08](https://user-images.githubusercontent.com/6259214/45266387-67d5ed00-b495-11e8-986f-872f5a37d189.png)

なお、ボタンを押しての投稿の場合は正常に動作します。
![screenshot from 2018-09-10 01-01-54](https://user-images.githubusercontent.com/6259214/45266398-9227aa80-b495-11e8-9fcf-039084fcd619.png)

動作環境: mikutter 3.8.0 (-twitterプラグイン +searchプラグイン改変)

**Comment by cobodo** [comment]
再現しませんでした。

実際、ショートカットキーからコマンドを起動しても、投稿ボタンを押しても、結局はmikutter本体の`core/mui/gtk_postbox.rb`にある`Gtk::PostBox#post_it`を呼ぶようになっていて、そこから（どちらの経路でも）同じように`compose` spellが呼び出されます。

Worldon側ではこの`compose` spellを実装することで、mikutter側から投稿を実行できるようにしてあるので、もし挙動に差異があるとしたらmikutter本体側や、他のプラグインで何か起こっているのかもしれません。

例えば、（何らかの条件で）`Gtk::PostBox`のインスタンス変数`@to`を上書きして空にしてしまうようなプラグインを入れているとそういった事が起こります。

Worldon以外のプラグインを全く入れない状態ではどうなりますか？

**Comment by kazu0617** [comment]
入れない状態で再現しませんでした。
以前別のプラグインに関してその問題が残っている（mikutter-emoji）
のを忘れてそのまま報告してしまいました…すみませんでしたm(_ _)m
