### ISSUE TITLE
ライセンスの変更 (BSD-3-Clause → MIT)

### ISSUE THREAD

**Issue by cobodo** [cobodo/mikutter-worldon#82]
mikutter本体側と整合を取るため、このプラグインのライセンスを、現在の3条項BSDライセンスから、MITライセンスへ変更したいと思っています。

これまでにpull requestを頂いた5人の方は、お手数ですが、賛成か反対かをこのissueに書いてほしいです。
@toshia 
@Akkiesoft 
@ncaq 
@kazu0617 
@moguno

よろしくお願いします。

**Comment by Akkiesoft** [comment]
👍

**Comment by moguno** [comment]
ええんちゃいます？

**Comment by toshia** [comment]
かまへんかまへん

**Comment by ncaq** [comment]
賛成

**Comment by cobodo** [comment]
ありがとうございました。ライセンスを変更しました。
今後ともよろしくお願いします。
