### ISSUE TITLE
Pleromaからのリプライの表示がおかしい

### ISSUE THREAD

**Issue by rinsuki** [cobodo/mikutter-worldon#91]
![image](https://user-images.githubusercontent.com/6533808/53428230-c5eb9200-3a2d-11e9-88c9-ac47f9dbc871.png)

**Comment by cobodo** [comment]
実は https://github.com/cobodo/mikutter-worldon/commit/5d5213c721c7075e9d17e6fe0bf888bb35177269 で対応済みです。
masterにはまだmergeしていませんが、developブランチでテストできます。
そのうちmergeすると思います。
